server:
  port: 8899
spring:
  application:
    name: feather-bz-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bz?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000 # 连接超时时间，单位毫秒
      idle-timeout: 600000 # 空闲连接超时时间，单位毫秒
      max-lifetime: 1800000 # 连接最大存活时间，单位毫秒
      validation-timeout: 5000 # 连接验证超时时间，单位毫秒
      leak-detection-threshold: 60000 # 连接泄漏检测阈值，单位毫秒
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志
    map-underscore-to-camel-case: true # 开启驼峰命名自动转换
  global-config:
    db-config:
      id-type: auto # 主键生成策略
      logic-delete-field: deleted # 逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  mapper-locations: classpath:mapper/*.xml # XML映射文件位置